import { Inter } from "next/font/google";
import "./globals.css";
import CookieWrapper from "@/components/cookie-wrapper";
import getServerDarkMode from "@/hooks/use-server-dark-mode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const theme = await getServerDarkMode();
  return (
    <html lang="en" className={theme}>
      <body className={`${inter.className} min-h-screen flex flex-col px-8`}>
        <CookieWrapper>{children}</CookieWrapper>
      </body>
    </html>
  );
}
